### ISSUE TITLE
Handle NAT

### ISSUE THREAD

**Issue by synapticvoid** [neuronalmotion/screenshare#3]
Because of NAT in IPv4, 2 users cannot discover each other without:
* Opening a port on their respective routers
* Connecting to a third party server

The real use case should be that the users simply fill out their unique id, and they connect.

**Comment by synapticvoid** [comment]
In IPv6, NAT simply disappeared. The address is unique (128bits divided in 2: subnet and device unique id).

Recent routers commonly support a dual configuration (IPv4/IPv6) and I'm pretty sure that all our computers already have an IPv6 address.

We might get away simply by making IPv6 mandatory to use screenshare. I can live with that, @GuillaumeLazar , is it OK for you ?

**Comment by GuillaumeLazar** [comment]
"IPv6 support" and "IPv4 support" could be two seperated features. 

IPv6 requirements:
- IPv6 on both computers

IPv4 requirements:
- IPv4 on both computers
- NAT and port forwarding if used across Internet

We should focus on one feature (let's say IPv6 support). But my point of view is that we can maybe factorize the code properly and add the ohter IPvx support for free now or later

It could be useful for a IPv4 local network or if someone dont care about open ports on his router.

**Comment by synapticvoid** [comment]
Good to me. Let's start with IPv6 for now, we might enable IPv4 in a fallback mode if IPv6 is not available.

I'm closing this issue for now, we'll open a dedicated one when we reach IPv4 support.
